### ISSUE TITLE
Plot Alignment settings are reversed

### ISSUE THREAD

**Issue by V1ral-101** [baatochan/SlimeRancherPlanner#20]
### The Issue:

When setting the "plot alignment" manually, the directions are reversed as to what they're listed as. Example, setting the alignment to Top Right will set the square to the Bottom Left instead.

### Possible Cause:

It seems that the Alignment descriptions are working on the assumption that the map is seen upside down from what it is currently set to.

### Possible Solution:

The Top & Bottom code sections could be interchanged with each other; similarly, the Left and Right code sections could do the same.

### Context

- Browser: Microsoft Edge

**Comment by baatochan** [comment]
This is intended behavior as the small square (when plot is empty) is in the position that description says.

So if you say that the plot is aligned top left then the small square is in the top left position of the bigger square. That's how I see it but if others will agree with your point of view I may change it.

**Comment by baatochan** [comment]
As noone responded I'm leaving things as they are.
