### ISSUE TITLE
Victors Update 1.4.0

### ISSUE THREAD

**Issue by happyfroggo** [baatochan/SlimeRancherPlanner#21]
With the new 1.4.0 update to slime rancher, there is a new area available, victor's lab.  Could you add in the new plots to the planner?

And if it is too much of a stretch, could you add in the areas for gadget sites to be placed in the ranch? like teleporters and portable water taps?

Thanks, 
H.

**Comment by CrazyBearTR** [comment]
I really think that we need the gadgets. Also I was just going to report the Viktor's place, but I guess thats already done. It may take some time though, if we consider the update is out for a week or so.

**Comment by baatochan** [comment]
1. I'll try my best to find time to update the app with Victor's plots. I can't promise any deadline but I hope it will be done in few weeks or something (TBH there is no much space left on this map and don't know where to put them).

2. In terms of gadgets there is already opened issue for that (#8) and I already explained the status of this feature. Any future messages about gadgets should be put there.

**Comment by baatochan** [comment]
Finnaly done, I'm really sorry that it took so long. If there are any problems regarding Victor's plots, just comment here.
