### ISSUE TITLE
Missing 'W' waterfall for the Docks area

### ISSUE THREAD

**Issue by mozai** [baatochan/SlimeRancherPlanner#23]
Victor and Mochi's ranches have 'W' plots for waterfalls.  The Docks area of Beatrix's ranch does not, but there is a waterfall for free-ranging puddle-slimes there.

**Comment by baatochan** [comment]
Couldn't reproduce that in the newest chrome running on windows. Could you provide more info on how to reproduce this bug?

Btw keep in mind that the waterfall in the docks is kinda hidden - you need to put your cursor over it to unhide :)

If there was a map for Mochi or Victor places I would make them hidden as well.

**Comment by mozai** [comment]
ohhh, I didn't know I had to mouse-over the waterfall in the ranch to make the [W] appear.  NOTABUG

If you need a map of Mochi ranch and Ogden's ranch, try [the map I found in Steam forums](https://steamuserimages-a.akamaihd.net/ugc/795360029431202423/4C5AB414428C6BC5A7F60C77BF7B146FB7E73AD6/)

**Comment by baatochan** [comment]
Thanks for linking me this map, it could be useful.
